name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update Makefile version
        run: |
          sed -i "s/VERSION=.*/VERSION=${VERSION}/" Makefile

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: bump version to ${VERSION}"
          git push

      - name: Run tests
        run: make test

      - name: Build binaries
        run: make build

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/darwin-amd64/kubeseal-encrypt-string
            build/darwin-arm64/kubeseal-encrypt-string
            build/linux-amd64/kubeseal-encrypt-string
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
