name: Release

on:
  push:
    tags:
      - 'v*' # Triggers on tags starting with "v"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Get Tag Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update Makefile Version
        run: |
          sed -i "s/VERSION=.*/VERSION=${VERSION}/" Makefile
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Makefile
          git commit -m "chore: bump version to ${VERSION}"
          git push origin main

      - name: Build Binaries
        run: make build

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: |
            ## Changes
            - Updated version to ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/darwin-amd64/kubeseal-encrypt-string
            build/darwin-arm64/kubeseal-encrypt-string
            build/linux-amd64/kubeseal-encrypt-string
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}